CREATE TYPE "public"."manager_actions" AS ENUM('create_time_slot', 'update_time_slot', 'delete_time_slot', 'create_user', 'update_user', 'create_booking', 'update_booking_status', 'move_booking', 'cancel_booking', 'manager_login', 'manager_logout', 'failed_login_attempt', 'password_change', 'assign_role', 'change_role', 'revoke_role', 'delete_manager', 'create_manager', 'create_banner', 'update_banner', 'delete_banner', 'change_configs', 'other');--> statement-breakpoint
CREATE TYPE "public"."banner_type" AS ENUM('image', 'video', 'gif');--> statement-breakpoint
CREATE TYPE "public"."booking_status" AS ENUM('advancePaid', 'fullPaid', 'fullPending', 'advancePending', 'wontCome', 'paymentFailed');--> statement-breakpoint
CREATE TYPE "public"."booking_type" AS ENUM('cricket', 'football', 'cricket&football');--> statement-breakpoint
CREATE TYPE "public"."customer_tag" AS ENUM('star', 'regular', 'vip', 'new');--> statement-breakpoint
CREATE TYPE "public"."gallery_media_type" AS ENUM('image', 'video');--> statement-breakpoint
CREATE TYPE "public"."gallery_status" AS ENUM('approved', 'inactive', 'discarded');--> statement-breakpoint
CREATE TYPE "public"."language" AS ENUM('en', 'ta');--> statement-breakpoint
CREATE TYPE "public"."manager_log_status" AS ENUM('success', 'failure', 'pending', 'waiting_for_approval');--> statement-breakpoint
CREATE TYPE "public"."roles" AS ENUM('admin', 'superAdmin', 'staff');--> statement-breakpoint
CREATE TYPE "public"."time_slot_status" AS ENUM('available', 'booked', 'unavailable', 'bookingInProgress');--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_account" (
	"id" text PRIMARY KEY NOT NULL,
	"accountId" text NOT NULL,
	"providerId" text NOT NULL,
	"userId" text NOT NULL,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" timestamp,
	"refreshTokenExpiresAt" timestamp,
	"scope" text,
	"password" text,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_banner" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Aruppukottai_turf_banner_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(100) NOT NULL,
	"description" text,
	"altText" varchar(256),
	"type" varchar(10) NOT NULL,
	"url" varchar(256) NOT NULL,
	"bannerType" "banner_type" DEFAULT 'image' NOT NULL,
	"language" "language" DEFAULT 'en' NOT NULL,
	"bannerIndex" integer DEFAULT 0 NOT NULL,
	"uploadedBy" integer,
	"createdAt" timestamp with time zone NOT NULL,
	"expireAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_booking" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"phoneNumber" varchar(20) NOT NULL,
	"timeSlotId" integer NOT NULL,
	"paymentId" varchar(255),
	"finalPaymentId" varchar(255),
	"couponId" uuid,
	"amountPaid" integer DEFAULT 0 NOT NULL,
	"totalAmount" integer NOT NULL,
	"verificationCode" varchar(4) NOT NULL,
	"bookingType" "booking_type" DEFAULT 'cricket' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone,
	"status" "booking_status" DEFAULT 'advancePending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_config" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Aruppukottai_turf_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"updatedBy" integer,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"maintenanceMode" boolean DEFAULT false NOT NULL,
	"maintenanceMessage" text DEFAULT '' NOT NULL,
	"fullPaymentMode" boolean DEFAULT false NOT NULL,
	"slotIntervalMinutes" integer DEFAULT 60 NOT NULL,
	"numberOfSlotsPerDay" integer DEFAULT 24 NOT NULL,
	"bookingBufferMinutes" integer DEFAULT 3 NOT NULL,
	"slotsVisibleDaysInAdvance" integer DEFAULT 4 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_coupon_use" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Aruppukottai_turf_coupon_use_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"couponId" uuid NOT NULL,
	"phoneNumber" varchar(20) NOT NULL,
	"bookingId" uuid NOT NULL,
	"usedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_coupon" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" varchar(50) NOT NULL,
	"description" text,
	"discountPercentage" integer NOT NULL,
	"maxDiscountAmount" integer DEFAULT 0 NOT NULL,
	"minimumPurchaseAmount" integer DEFAULT 0 NOT NULL,
	"validFrom" date NOT NULL,
	"validTo" date NOT NULL,
	"usageLimit" integer DEFAULT 0 NOT NULL,
	"numberOfUses" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "Aruppukottai_turf_coupon_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_customer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Aruppukottai_turf_customer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100),
	"number" varchar(20) NOT NULL,
	"email" varchar(256),
	"alternateContactName" varchar(100),
	"alternateContactNumber" varchar(20),
	"languagePreference" "language" DEFAULT 'en' NOT NULL,
	"tag" "customer_tag" DEFAULT 'new' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "Aruppukottai_turf_customer_number_unique" UNIQUE("number")
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_gallery" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Aruppukottai_turf_gallery_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(200) NOT NULL,
	"description" text,
	"altText" varchar(256),
	"mediaType" "gallery_media_type" DEFAULT 'image' NOT NULL,
	"status" "gallery_status" DEFAULT 'approved' NOT NULL,
	"cloudinaryPublicId" varchar(255) NOT NULL,
	"cloudinaryUrl" varchar(512) NOT NULL,
	"thumbnailUrl" varchar(512),
	"credits" varchar(200),
	"phoneNumber" varchar(20),
	"displayOrder" integer DEFAULT 0 NOT NULL,
	"uploadedBy" integer,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "Aruppukottai_turf_gallery_cloudinaryPublicId_unique" UNIQUE("cloudinaryPublicId")
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_manager_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Aruppukottai_turf_manager_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"managerId" integer NOT NULL,
	"action" "manager_actions" DEFAULT 'other' NOT NULL,
	"details" jsonb,
	"status" "manager_log_status" NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_manager" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Aruppukottai_turf_manager_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"authId" text NOT NULL,
	"role" "roles" DEFAULT 'staff' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "Aruppukottai_turf_manager_authId_unique" UNIQUE("authId")
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_session" (
	"id" text PRIMARY KEY NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"token" text NOT NULL,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp NOT NULL,
	"ipAddress" text,
	"userAgent" text,
	"userId" text NOT NULL,
	CONSTRAINT "Aruppukottai_turf_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_time_slot" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "Aruppukottai_turf_time_slot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"from" time NOT NULL,
	"to" time NOT NULL,
	"date" date NOT NULL,
	"status" time_slot_status DEFAULT 'available' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone,
	"updatedBy" integer
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"emailVerified" boolean NOT NULL,
	"image" text,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp NOT NULL,
	CONSTRAINT "Aruppukottai_turf_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "Aruppukottai_turf_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"createdAt" timestamp,
	"updatedAt" timestamp
);
--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_account" ADD CONSTRAINT "Aruppukottai_turf_account_userId_Aruppukottai_turf_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."Aruppukottai_turf_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_banner" ADD CONSTRAINT "Aruppukottai_turf_banner_uploadedBy_Aruppukottai_turf_manager_id_fk" FOREIGN KEY ("uploadedBy") REFERENCES "public"."Aruppukottai_turf_manager"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_booking" ADD CONSTRAINT "Aruppukottai_turf_booking_phoneNumber_Aruppukottai_turf_customer_number_fk" FOREIGN KEY ("phoneNumber") REFERENCES "public"."Aruppukottai_turf_customer"("number") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_booking" ADD CONSTRAINT "Aruppukottai_turf_booking_timeSlotId_Aruppukottai_turf_time_slot_id_fk" FOREIGN KEY ("timeSlotId") REFERENCES "public"."Aruppukottai_turf_time_slot"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_booking" ADD CONSTRAINT "Aruppukottai_turf_booking_couponId_Aruppukottai_turf_coupon_id_fk" FOREIGN KEY ("couponId") REFERENCES "public"."Aruppukottai_turf_coupon"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_config" ADD CONSTRAINT "Aruppukottai_turf_config_updatedBy_Aruppukottai_turf_manager_id_fk" FOREIGN KEY ("updatedBy") REFERENCES "public"."Aruppukottai_turf_manager"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_coupon_use" ADD CONSTRAINT "Aruppukottai_turf_coupon_use_couponId_Aruppukottai_turf_coupon_id_fk" FOREIGN KEY ("couponId") REFERENCES "public"."Aruppukottai_turf_coupon"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_coupon_use" ADD CONSTRAINT "Aruppukottai_turf_coupon_use_phoneNumber_Aruppukottai_turf_customer_number_fk" FOREIGN KEY ("phoneNumber") REFERENCES "public"."Aruppukottai_turf_customer"("number") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_coupon_use" ADD CONSTRAINT "Aruppukottai_turf_coupon_use_bookingId_Aruppukottai_turf_booking_id_fk" FOREIGN KEY ("bookingId") REFERENCES "public"."Aruppukottai_turf_booking"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_gallery" ADD CONSTRAINT "Aruppukottai_turf_gallery_uploadedBy_Aruppukottai_turf_manager_id_fk" FOREIGN KEY ("uploadedBy") REFERENCES "public"."Aruppukottai_turf_manager"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_manager_log" ADD CONSTRAINT "Aruppukottai_turf_manager_log_managerId_Aruppukottai_turf_manager_id_fk" FOREIGN KEY ("managerId") REFERENCES "public"."Aruppukottai_turf_manager"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_manager" ADD CONSTRAINT "Aruppukottai_turf_manager_authId_Aruppukottai_turf_user_id_fk" FOREIGN KEY ("authId") REFERENCES "public"."Aruppukottai_turf_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_session" ADD CONSTRAINT "Aruppukottai_turf_session_userId_Aruppukottai_turf_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."Aruppukottai_turf_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Aruppukottai_turf_time_slot" ADD CONSTRAINT "Aruppukottai_turf_time_slot_updatedBy_Aruppukottai_turf_manager_id_fk" FOREIGN KEY ("updatedBy") REFERENCES "public"."Aruppukottai_turf_manager"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "coupon_use_couponid_phonenumber_unique_idx" ON "Aruppukottai_turf_coupon_use" USING btree ("couponId","phoneNumber","bookingId");--> statement-breakpoint
CREATE INDEX "user_number_idx" ON "Aruppukottai_turf_customer" USING btree ("number");--> statement-breakpoint
CREATE INDEX "gallery_display_order_idx" ON "Aruppukottai_turf_gallery" USING btree ("displayOrder");--> statement-breakpoint
CREATE INDEX "gallery_status_idx" ON "Aruppukottai_turf_gallery" USING btree ("status");--> statement-breakpoint
CREATE INDEX "gallery_phone_number_idx" ON "Aruppukottai_turf_gallery" USING btree ("phoneNumber");--> statement-breakpoint
CREATE UNIQUE INDEX "time_slot_from_to_date_unique_idx" ON "Aruppukottai_turf_time_slot" USING btree ("from","to","date");